# baseURL = "https://lets-remember.github.io/"
languageCode = "en-us"
title = "thinks.lol"
defaultContentLanguage = "en"
# todo: multiple languages possible


[permalinks]
posts = "/:year/:month/:title/"
