# baseURL = "https://thinks.lol/"
languageCode = "en-us"
title = "thinks.lol"
defaultContentLanguage = "en"
# todo: multiple languages possible
enableRobotsTXT = true
rssLimit = 1000

[params]
customCSS = ["css/custom.css"]

[permalinks]
posts = "/:year/:month/:title/"
