
[[main]]
name = "About"
url = "/about/"
weight = 2

[[main]]
name = "RSS"
url = "/index.xml"

[[footer]]
name = "Github"
url = "https://github.com/ekg"
weight = 1

[[footer]]
name = "twitter/X"
url = "https://x.com/erikgarrison"
weight = 2

[[footer]]
name = "Mastodon"
url = "https://mastodon.social/@ekg"
weight = 3

[[footer]]
name = "BlueSky"
url = "https://bsky.app/profile/thinks.lol"
weight = 4